spring:
   datasource:
      username: game_catalog
      password: game_catalog
      url: jdbc:mysql://localhost:3306/game_catalog
      
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true